# Generated by Django 3.2.5 on 2021-08-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkwaxyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(upload_to='kkwaxyApp\\images', verbose_name='Media'),
        ),
    ]
