# Generated by Django 3.2.5 on 2021-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkwaxyApp', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, default='Ajouter le corps du texte ici.', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Introduction'),
        ),
    ]
