# Generated by Django 3.2.5 on 2021-09-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkwaxyApp', '0005_auto_20210801_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(verbose_name='Introduction'),
        ),
    ]
