# Generated by Django 3.2.5 on 2021-08-01 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('article', models.TextField(max_length=500, verbose_name='Arcticle')),
                ('media', models.FileField(upload_to='images', verbose_name='Media')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
