# Generated by Django 3.2.5 on 2022-08-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkwaxyApp', '0007_auto_20220808_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
    ]
